"""Add user model

Revision ID: f5a8cb5b7178
Revises: 150be163622d
Create Date: 2026-03-23 02:08:23.699391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5a8cb5b7178'
down_revision: Union[str, Sequence[str], None] = '150be163622d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Очистка таблицы products перед добавлением нового столбца
    op.execute("DELETE FROM products") 



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
